//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieQuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int MovieId { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
